# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-02 11:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='用户名称', max_length=32)),
                ('age', models.IntegerField(default=1, help_text='年龄')),
                ('gender', models.CharField(default='male', help_text='性别', max_length=8)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('birthday', models.CharField(default='暂无详细生日信息', max_length=128)),
                ('address', models.CharField(default='暂无详细地址', help_text='地址，多对一', max_length=128)),
                ('phone', models.CharField(blank=True, default='', help_text='电话', max_length=16, null=True)),
                ('qq', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('wechat', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', help_text='地址', max_length=128)),
                ('product_id', models.CharField(default='', help_text='商品id', max_length=128)),
                ('total_moeny', models.FloatField(default=0, help_text='订单价格')),
                ('buyer', models.ForeignKey(help_text='订单', on_delete=django.db.models.deletion.CASCADE, to='Mymall.Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='商品名称', max_length=64)),
                ('category_id', models.CharField(max_length=20)),
                ('price', models.FloatField(help_text='商品价钱')),
                ('keywords', models.CharField(default='', help_text='搜索关键字', max_length=20)),
                ('describe', models.TextField(default='暂无描述信息', help_text='描述信息')),
                ('create_date', models.DateTimeField(auto_now=True, help_text='发布时间')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=20)),
                ('features', models.TextField(default='暂无特征描述')),
                ('modeltype', models.CharField(default='暂无详细型号', max_length=64)),
                ('displaysize', models.CharField(blank=True, default='', help_text='显示屏尺寸', max_length=32)),
                ('dimensions', models.CharField(default='', help_text='规格', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='卖家名称', max_length=32)),
                ('age', models.IntegerField(default=1, help_text='年龄')),
                ('gender', models.CharField(default='male', help_text='性别', max_length=8)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, default='', help_text='手机号码', max_length=16, null=True)),
                ('qq', models.CharField(blank=True, default='', help_text='QQ', max_length=16, null=True)),
                ('wechat', models.CharField(blank=True, default='', help_text='微信号', max_length=64, null=True)),
                ('product', models.ForeignKey(help_text='商品', on_delete=django.db.models.deletion.CASCADE, to='Mymall.Product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0, help_text='余额')),
                ('buyer', models.OneToOneField(help_text='买家用户', on_delete=django.db.models.deletion.CASCADE, to='Mymall.Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='WalletFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, help_text='差额')),
                ('direction', models.BooleanField(default=True, help_text='方向,增加为True,减少为False')),
                ('create_date', models.DateTimeField(auto_now=True, help_text='发生时间')),
                ('reason', models.CharField(help_text='变动原因', max_length=32)),
                ('done', models.BooleanField(default=False, help_text='是否已完成')),
                ('payment', models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信')], help_text='支付方式', max_length=32)),
                ('paymentid', models.CharField(help_text='第三方支付id', max_length=128)),
                ('wallet', models.ForeignKey(help_text='钱包', on_delete=django.db.models.deletion.CASCADE, to='Mymall.Wallet')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_info',
            field=models.OneToOneField(help_text='商品详细信息', on_delete=django.db.models.deletion.CASCADE, to='Mymall.ProductInfo'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(help_text='订单', on_delete=django.db.models.deletion.CASCADE, to='Mymall.Seller'),
        ),
    ]
