"""empty message

Revision ID: 603b04a5dd8d
Revises: a400c355df3d
Create Date: 2018-06-30 08:25:06.295488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603b04a5dd8d'
down_revision = 'a400c355df3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('superuser_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'superuser', ['superuser_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'superuser_id')
    # ### end Alembic commands ###
