"""empty message

Revision ID: 7aa5c1a67dce
Revises: 521ce838dbdf
Create Date: 2018-06-26 19:04:57.105964

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7aa5c1a67dce'
down_revision = '521ce838dbdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
