"""empty message

Revision ID: 94f123968a31
Revises: 7aa5c1a67dce
Create Date: 2018-06-26 19:33:42.951846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94f123968a31'
down_revision = '7aa5c1a67dce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('selfread', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'selfread')
    # ### end Alembic commands ###
