"""empty message

Revision ID: a400c355df3d
Revises: cd68f0dfb7ca
Create Date: 2018-06-29 22:14:10.100478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a400c355df3d'
down_revision = 'cd68f0dfb7ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('superanduser',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('superuser_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['superuser_id'], ['superuser.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('superanduser')
    # ### end Alembic commands ###
